### ISSUE TITLE
Мелочи пофиксить

### ISSUE THREAD

**Issue by Domerk** [aizenbit/Scribbler#1]
- [x] ~~Иконка сохранения в редакторе шрифтов~~
- [x] Вставить обратно запрет на соединение не букв
- [x] Цвет точек соединения в редакторе - он должен контрастировать с тем цветом, которым нарисована буква, иначе их не видно
- [x] Вероятно, добавить автоматическую установку точек в начало и конец линии, если линия одна

**Comment by aizenbit** [comment]
Спасибо! =)

С соединением не букв разобрался, цвет точек стал немного ярче. Остальное позже.

**Comment by Domerk** [comment]
Молодец :+1:

**Comment by aizenbit** [comment]
Иконку сохранения, наверное, нафиг. Не могу представить, что такого может сделать юзер в редакторе шрифтов, чтобы помнить о необходимости часто сохраняться было проще, чем исправить ошибку. Разве что случайное нажать на "Отмену" после долгой работы, но это надо решать другим способом.

Автоматическая установка точек всё ещё кажется хорошей идеей, но откладывается на потом.

**Comment by aizenbit** [comment]
Добавил автоматическую установку точек в начало линии. Думаю, установку точек нужно делать даже если линия не одна, тогда одна точка устанавливается в начало первой линии, а вторая - в конец последней.

**Comment by aizenbit** [comment]
Добавил автоматическую установку точек в конец последней линии. Правда, я сделал это, ориентируясь лишь на тот набор символов, который у меня уже есть, так что, скорее всего, на другом наборе символов будут проблемы. Но как временное решение сойдёт.
